= High-Performance dApps

== What is a High-Performance dApp?

A high-performance decentralized application (dApp) is a type of application that is designed and optimized to deliver superior performance in terms of speed, scalability, and throughput, compared to traditional decentralized applications.

Key characteristics of a high-performance dApp include:

- *Speed*: High-performance dApps aim to provide fast and responsive user experiences. By using the SKALE Network, high performance dApps are able to minimize transaction confirmation times and reduce latency to ensure quick interactions and seamless user interactions.

- *Scalability*: High-performance dApps are designed to scale efficiently as the user base and transaction load increase. Leveraging SKALE's multi-chain setupallows applications to host a large number of concurrent users and transactions without sacrificing performance or harming the rest of the applications on the network.

- *Throughput*: High-performance dApps can push a significant volume of transactions per second (TPS). Individual SKALE Chains can support on average 200 transaction per second with peak up to 700 transactions per second. Additinally, applications on dedicated chains are also able to offload common actions such as token swaps, NFT listings, and more to shared hub chains.

- *Zero Cost Transactions*: High-performance dApps cannot afford to subsidize user transactions with variable gas amounts. SKALE Chains utilize a zero economic value gas token called SKALE Fuel ("sFUEL") which enables all transactions on a chain to be free, opening the door for doing more complex operations in Solidity that would not be feasible on value-gas chains.

- *Flexible Infrastructure*: High-performance dApps can both grow quickly and experience large spikes in usage. SKALE Network offers flexible infrastructure by allowing companies to run their own proxies, sync nodes, and other key peripheral components to scale according to their specific needs.

== Developer Resources

The following are some key developer resources commonly used within by high-performance dApps.

=== Multi-Transaction Mode (MTM)

Multi-Transaction Mode enables extremely high throughput onto a SKALE Chain as well as enabling additional large bursts of traffic. See xref:mtm-mode.adoc[here].
