[.card-section]
= Documentation

Explore documentation about the SKALE Network, developing on SKALE, validating and delegating, and about SKALE's technologies.

[.card.card-learn]
--
xref:_ethereum_native[[.card-title]#Ethereum Native# [.card-body]#pass:q[Built, supported and aligned with Ethereum.]#]
--
[.card.card-learn]
--
xref:_multichain[[.card-title]#Multichain# [.card-body]#pass:q[Supports an unlimited number of chains.]#]
--
[.card.card-learn]
--
xref:skaled::index.adoc[[.card-title]#SKALE Chain# [.card-body]#pass:q[Enabling dApps to run decentralized, fast and cost-effectively.]#]
--
[.card.card-learn]
--
xref:filestorage::index.adoc[[.card-title]#Filestorage# [.card-body]#pass:q[A Web3 storage layer available on each chain.]#]
--
[.card.card-learn]
--
xref:ima::index.adoc[[.card-title]#Interchain Messaging Agent# [.card-body]#pass:q[An Ethereum - SKALE bridge using threshold cryptograph.]#]
--
[.card.card-learn]
--
xref:validators::delegation.adoc[[.card-title]#Delegation# [.card-body]#pass:q[Delegate SKL tokens to validators.]#]
--
[.card.card-learn]
--
xref:validators::index.adoc[[.card-title]#Validators# [.card-body]#pass:q[Run SKALE Nodes to support the SKALE Network.]#]
--
[.card.card-learn]
--
link:https://github.com/skalenetwork[[.card-title]#Open Source# [.card-body]#pass:q[Code and development is open sourced.]#]
--

== About SKALE Network

The SKALE Network is a highly expandable multichain blockchain network that serves as a secure Ethereum scalability solution. Unlike most Layer 1 and Layer 2 networks, the SKALE architecture is built to support an ever-expanding set of dapp-specific chains. It uses the Ethereum mainnet to manage and orchestrate many critical network operations thereby enhancing overall network security and transparency.

What does this mean? It means running your dApp on a scalable and fast chain provisioned exclusively for your dApp and ecosystem, without the worry of gas constraints, with all the connections to Ethereum Mainnet that you, your users, and your community need. It means having access to decentralized storage, web servers, and message transfer all on the same chain.

=== Ethereum Native

* SKALE is built on Ethereum. Yes, it's Inception-level stuff – a network within a network. The entire operation and orchestration of the SKALE network is conducted via a series of smart contracts on Ethereum called SKALE Manager.
* SKALE is built with Ethereum technology. SKALE Chains run an EVM client based on Ethereum's Aleth client. 
* SKALE is interoperable with Ethereum. The Ethereum-SKALE bridge called Interchain Messaging Agent (IMA) allows transferring of any token standard or message between Ethereum and SKALE, using BLS Threshold cryptography to secure transfers.
* SKALE support for Solidity and the Ethereum VM extends to commonality with Ethereum protocols and developer tools. You can use the same tools, wallets, token standards, etc. as you do with the Ethereum mainnet.
* SKALE is incentively aligned with Ethereum. SKALE Network operations such as SKALE Chain creation, validator registration, delegation, etc., all are transactions on Ethereum mainnet and handled by SKALE Manager. So SKALE Network is secured by Ethereum and drives mining fees back to Ethereum miners.

=== Multichain

SKALE Network can support an unlimited number of chains that are purpose-built for Web3 dapps.

=== SKALE Chains

A scalable Web3 sidechain instance sharing resources across a randomized set of 16 nodes, enabling dApps to run fast and cost-effectively in a 16-node decentralized manner.

=== Filestorage

A scalable Web3 storage layer on each SKALE Chain, enabling dApp Developers to leverage decentralized storage right on their SKALE Chain.

=== Interchain Messaging Agent (IMA)

An Ethereum-SKALE bridge allowing transfer of tokens and messages between SKALE Chains and Ethereum.

=== Delegation

SKALE token holders can delegate/stake tokens to validators by interacting with SKALE Manager contracts on Ethereum. Delegators receive monthly bounty rewards for performing this service.

=== Validation

Validators run SKALE nodes that support SKALE Chains and IMA. Each node must meet specific network, software, and staking requirements to register with the network. Nodes work together to create and sign blocks on multiple SKALE Chains.

=== Open Source

SKALE Network code and development are all open source. See the GitHub repository at <https://github.com/skalenetwork>.

== Security Audits

SKALE Network security audits are performed on a periodic and regular basis. To learn more about SKALE Network audits, please find audit reports under the respective repository. https://skale.network/security[Click here for more information on SKALE Network's security policy].

== More 

See the https://skale.network[main website].

Follow the community's open-source development on https://github.com/skalenetwork[GitHub]

== Questions?

Join the SKALE Network developer community http://skale.chat[Discord server].


== Resources

* https://skale.network/blog/technical-highlights/[Technical Highlights]
* https://skale.network/blog/the-power-of-ethereum-a-blockchain-created-by-a-blockchain/[The Power of Ethereum: A blockchain created by a blockchain/]
* https://skale.network/blog/why-multichain-networks-matter-and-other-advantages-of-skale-chains/[Why Multichain networks Matter and other Advantages of SKALE Chains]
* https://skale.network/blog/the-skl-token-and-ethereum-mainnet-fees/[The SKL Token and Ethereum Mainnet fees]
* https://skale.network/blog/introduction-of-the-skale-ima-bridge/[Introduction of the SKALE IMA Bridge]
* https://skale.network/blog/containerization-the-future-of-decentralized-infrastructure/[Containerization: The Future of Decentralized Infrastructure]
* https://skale.network/blog/containerization-the-future-of-decentralized-infrastructure-2[Containerization: The Future of Decentralized Infrastructure, part 2]
* https://skale.network/blog/the-skale-network-validator-faq/[The SKALE Network Validator FAQ]
* https://skale.network/blog/delegators/[Delegators]
