= SKALE Chains

A SKALE Chain is a Web3 Ethereum compatible elastic blockchain designed to make Web3 cloud computing easier for dApp developers. SKALE Chains provide EVM compute power, decentralized database storage, and other functionality to help not only power your dApps but allow them to scale in a cost-effective manner. 

== What makes a SKALE Chain

SKALE Chains are powered by dockerized containers provisioned across 16 randomly selected nodes from a network of >150 nodes. Nodes are operated by over 45 independent validator organizations. Each node supporting SKALE Chains is secured by Proof-of-Stake from the validator and delegator communities.

Every node in the SKALE Network dynamically supplies containerized Web3 compute resources that work in concert with other nodes. A SKALE Chain involves 16 randomly chosen nodes that each run containerized network clients with EVM (skaled) and other functions. All 16 of these skaled containers broadcast network messages, share transactions and blocks, and other cryptographic data with each other. These containers represent powerful and scalable instances of an Ethereum network, receiving Web3 transactional messages from clients and end-users, organizing them into blocks using an ultra-fast mathematically proven consensus called Asynchronous Binary Byzantine Agreement.

== How to work with a SKALE Chain

Each SKALE Chain powers dApps and their communities, providing dedicated Web3 compute resources to support dApp EVM execution and transactions from end-users.

Using SKALE is easy! Don't worry about https://github.com/skalenetwork/SGXWallet[SGX enclaves], https://github.com/skalenetwork/libBLS[BLS threshold signatures], and https://github.com/skalenetwork/skale-consensus[Asynchronous Binary Byzantine Consensus] - all this technology works under the hood to provide dApp developers with scalable and easy to run dApp-specific blockchains. 

You use your SKALE Chain as you work with Ethereum. SKALE Chain owners have a set of 16 available endpoints to receive Web3 transactions and data. Plug an endpoint into your Web3 client or Truffle config, and you are using SKALE.

To work with other blockchains like Ethereum Testnets or Mainnet, you can use xref:ima::index.adoc[a bridge called Interchain Messaging Agent (IMA)]. IMA allows the transfer of ETH, ERC20, ERC721, ERC1155, and other arbitrary messages between Ethereum and SKALE Chains.

== How to stake/create a SKALE Chain

To stake a SKALE Chain, you stake SKALE tokens (SKL) into the Network over a length of time. Every month, a portion of your stake is distributed to the entire Network in return for receiving security and scalable resources powering your SKALE Chain. At the end of your stake, anyone can stake additional SKL tokens to extend the SKALE Chain's life .

Creating a SKALE Chain requires SKL tokens and some ETH to fund the necessary transactions on Ethereum to create the SKALE Chain. When you create a SKALE Chain, you will fund some ETH to a special wallet. This wallet is used to reimburse transactions conducted by validator-nodes that form your SKALE Chain. Just as anyone can stake additional SKL to extend the SKALE Chain life, anyone with the wallet address can replenish ETH to fund additional SKALE Chain-related transactions. xref:validator-cli::self-recharging-wallets.adoc[More on these transactions and special wallets here.]

== SKALE Chain Features

* **Decentralized and permissionless network** where dApps run on chains supported by a randomly selected group of validator nodes, and nodes are swapped from time to time. The entire Network runs from the Ethereum Network to provide a permissionless way to access Web3 cloud resources.
* **Native cross-chain integration** using Ethereum and SKALE IMA – allows users to move tokens, state, and messages between Ethereum and SKALE Chains, and between SKALE Chains. This bridge is secured by stake, secure enclaves, and BLS Threshold cryptography.
* **Web3 RPC API** so existing dApps can migrate to SKALE Chains with minimal change and developers can use Ethereum tooling such as Truffle, Metamask, Remix, etc.
* **Customized for your dApp**: configure Web3 cloud resources specific to your dApp and end-users' needs. This includes various SKALE Chain sizes to support different levels of compute and storage resources and custom options for DDoS protection, node rotation, and more.
* **Decentralized SKALE Chain Administration** that can be operated by a single entity, community, or a DAO. This provides a range of decentralization options for funding, operating, and maintaining SKALE Chains.
