= Basics of SKALE Network

== SKALE Network & What it does

The SKALE is an Ethereum native multichain network of high-performance blockchains. The network is open-source and is built to scale Ethereum dApps. The Network enables dApp developers to access validator-operated nodes' compute power and storage to run fast, containerized, EVM-compatible SKALE Chains. Validators run and maintain SKALE Nodes, providing distributed computing power and storage to the SKALE Network. 

The entire SKALE Network is managed by SKALE Manager which is a set of over 35 smart contracts deployed on Ethereum Mainnet. These contracts control network functions such as chain creation, validator registration, node selection, node rotation, staking, bounty payment, slashing, and more.  Network users such as validators, delegators, and dApp Developers exchange SKALE (SKL) tokens to provide stake and access network services.

The https://skale.network/blog/validator-list-for-skale/[SKALE validator community represents over 45 independent operators] running over 150 nodes, and the SKALE Mainnet has been live for over 300 days without interruption. https://countdown.skale.network/[Checkout the current stats.]

With SKALE, dApps run zero-cost transactions on a Proof-of-Stake chain distributed across a randomly chosen set of 16 nodes, each running a containerized EVM. SKALE chains can exchange transactions or messages with other SKALE Chains and Ethereum-based networks, allowing dApp developers to use SKALE for powering their dApps while enabling token and message transfers to and from Ethereum or other chains.

SKALE Network uses a https://skale.network/blog/technical-highlights/[unique combination of technologies and cryptographic-based approaches] to achieve scalability, security, interoperability, and progressive decentralization:

[%header,cols=2*]
|===
|Technology 
|Impact

|Pooled Validation Proof-of-Stake
| https://skale.network/blog/the-skale-network-why-randomness-rotation-and-incentives-are-critical-for-secure-scaling/[Scalable security model across validators and delegators]

| Hybrid container architecture
| https://skale.network/blog/containerization-the-future-of-decentralized-infrastructure/[Agile allocation of on-demand composable compute resources across the network]

|Threshold Cryptography
| Supermajority signature signing with ABBA consensus supports Byzantine Fault Tolerance and resolves https://skale.network/blog/the-data-availability-problem/[data-availability] issues  

|Trusted-Execution Environment
| https://github.com/skalenetwork/SGXWallet[Fast block signing and multiple chain support using threshold cryptography]

|Asynchronous Binary Byzantine Agreement (ABBA) Consensus
| https://skale.network/blog/skale-consensus/[Mathematically provable, fast-finality, leaderless, and Byzantine fault tolerant]

|Ethereum Network
|Public, open-source, and decentralized operation of the SKALE Network via SKALE Manager contracts

|===

== Tools & Compatibility

SKALE Network is designed to work with all Ethereum compatible tools such as API-based wallets and monitoring and analytics. 

xref:develop::index.adoc#_developer_tool_docs[View Tools]

== Access a SKALE Chain

If you don't have a SKALE Chain yet, you can get started by using the public SKALE Chain, Chaos Testnet.
Checkout the xref:develop::index.adoc#_get_a_skale_endpoint[Develop Page] to access chain information like rpc endpoint and chain id as well as learn how to attain sFUEL.

// Commented Until New Link is Available
// * https://skale.network/innovators-signup[Apply to SIP Program] for a chance to receive a SKALE Mainnet chain grant.

Still not sure how to get started? Then head over to the xref:develop::index.adoc[Develop Page] or reach out to the https://discord.gg/skale[SKALE Network developer community on Discord].

== Engage with SKALE Network Community

* Discord - For development and validator-focused discussions, join the https://discord.gg/skale[SKALE Network Discord channel].
* Telegram - For general and non-technical discussions, https://t.me/skaleofficial[join the Telegram group].
* Twitter - Follow https://twitter.com/SkaleNetwork[@SkaleNetwork] on Twitter.
* YouTube - For video-tutorials and related content, subscribe to the SKALE YouTube channel https://www.youtube.com/skale[here].
* Blog - Follow and subscribe to the SKALE Network blog and newsletter https://skale.space/blog[here].
