= Frequently Asked Questions (FAQs)

== General

=== How does the SKALE Network work?

The SKALE Network consists of a large set of nodes, all running concurrently and independently, validating transactions within the SKALE Chain they oversee. These nodes coordinate with a set of smart contracts that run on the Ethereum mainnet called SKALE Manager. SKALE Manager includes SKALE Token that governs its issuance and how rewards get distributed to validators and delegators. These smart contracts are also where the network analysis takes place and where corrective actions are taken if there is bad behavior by one or more nodes.

Developers request a specific size chain (small, medium, and large), chain duration (180, 365, 730 days aka 6, 12, 24 months), and then stake SKALE tokens to complete the provisioning of the chain. These tokens get staked into SKALE Manager on Ethereum mainnet. Each month, some tokens from this developer's stake move into a bounty pool which is then used to reward the validators and delegators within the network. Inflation (issuance) event occurs each month whereby new SKALE tokens are created, which gets pushed into the bounty pool for reward to validators and delegators.

For example, suppose there are a thousand validator nodes in the network, and they all perform well. In that case, they will each participate in the monthly proceeds from the bounty pool, which includes a portion of the sidechain token stakes plus an inflation amount. The distribution to the validators isn't necessarily shared equally. A modifier component slightly adjusts the payout based on the stake duration. Nodes with tokens that locked for twelve months, for example, will receive a more significant percentage than those locked up for three or six months.

=== How does the network work from an operational and governance perspective?

The SKALE Network is a custodial execution layer (Layer 2). Whereas non-custodial approaches use a system of fraud proofs to allow funds to move between chains, SKALE makes use of BLS threshold signatures, deposit boxes within the Ethereum mainnet, and other mechanisms to allow for custodial ownership and use within the network (which will enable it to leverage the security guarantees of the mainnet but gain the performance inherent in Layer 2).

The stake from the validators or developers, and the token inflation, is coordinated through SKALE Manager contracts on Ethereum mainnet and SKALE nodes in the SKALE Network.

This approach is different from other Layer 2 models that attempt to use mainnet interactions to run verification or fraud proofs. SKALE uses the Ethereum mainnet for staking and other mechanistic operations in a way that's better attuned to creating a robust and trustworthy Layer 2 network. SKALE will also support BLS Rollups for use cases that require complete reliance on MainNet custody.

=== What benefits do virtualized subnodes and node containerization provide?

Each sidechain comprises a collective of randomly appointed virtualized subnodes that run a containerized SKALE EVM-client daemon (skaled) and SKALE consensus. Nodes in the SKALE Network aren't restricted to operating a single chain but instead can support multiple sidechains via virtualized subnodes. This multiplex capability is made possible via a containerized subnode architecture deployed on each node in the network. Each node is virtualized and can participate as a validator via this subnode architecture for an independent number of sidechains. Sidechains sizes can be small, medium, or large, with a small chain using 1/128 of a node's resources, a medium using 1/8 of the resources, and a large using the total amount. Currently, only medium SKALE chains will be available for the early phases of the network.

The subnode virtualization is enabled via an innovative containerized architecture that provides industrial-grade performance and optionality for decentralized application developers – performance and flexibility that's similar to traditional centralized cloud and microservice systems. Containers are divided into several main components encapsulated via a dockerized Linux OS, allowing each node to be hosted in an OS-agnostic manner.

=== What differentiates the SKALE token from others?

SKL is a utility token with four functions. It's important to understand that a certain amount of tokens will always be staked and that tokens will be needed to pay for SKALE Chains.
The four primary functions:

. security of and staking in the network

SKL token holders (delegators) stake their SKL tokens to validators who run nodes that make the SKALE network function by validating blocks, executing smart contracts, and securing the network. They're rewarded with SKL tokens for their efforts.

.Subscription access to network resources

Developers provision their subscription access to SKALE Chains using SKL tokens.

.Rewards for validators and delegators staking their tokens

Rewards are accumulated monthly, based on developer stake for chains and monthly inflation of tokens into the network.

. governance and voting

SKL tokens will be used for on-chain voting, which will control all economic parameters of the SKALE Network.

More details about the SKALE token are here: https://skale.network/token/

=== What's a SKALE Chain?

A SKALE Chain is an Ethereum Native Web3 Ethereum compatible sidechain making Web3 cloud computing easier for dApp developers. SKALE Chains provide EVM compute power, decentralized database storage, and other functionality to help not only power your dApps but allow them to scale in a cost-efficient manner.

=== What's the governing body for the SKALE Network?

The governing body for the network is the N.O.D.E. Foundation. The Foundation believes that validators must play a primary role in policing. Given their responsibility to the network, validators are highly incentivized to act in their best interest in guarding and preserving the integrity of the network.

The Network of Decentralized Economics (N.O.D.E.) Foundation based in Liechtenstein has been created to carry out the mission of supporting the SKALE Network. The SKALE Network is designed to support businesses, people, organizations that run on the open internet.

The SKALE Network is governed by its code which includes the SKL token. Onchain voting will be required to change any economic principles of the protocol.

The Foundation will support the network by electing a diverse set of Network Representatives. These representatives will ideally comprise dApp developers who run SKALE Chains, validators who run SKALE Nodes, independents such as investors who helped kickstart the network economics, and developers/representatives that actively build, maintain, and evolve the codebase. These representatives will serve the community by facilitating on-chain voting, grants, and budget/treasury decisions. The representatives will be selected by the Foundation initially; however, future elections will be held via a variant of on-chain voting by token holders to choose representatives that facilitate on-chain voting.
Ten percent of the total pool of SKL tokens is allocated to the Foundation and is vested over seven years to provide it with a budget and resources to fulfill its mission.

=== When are Governance proposals scheduled?

The process for governance proposals is still under development. Look for future updates in the announcement channels as well as on telegram here https://t.me/skalefoundation[https://t.me/skalefoundation].

The Product Team is working on the plans, https://skale.network/roadmap[see the current roadmap here].

=== Why is the SKALE token an ERC777?

ERC-777 offers unique pre-transfer checks that facilitate locking and delegation mechanisms within the SKALE Network while being backward compatible with ERC-20. The added benefit is that managing ownership over a delegator's token is simplified. With ERC-777, a delegated token never leaves the user's wallet–it's simply locked from any further actions. 

The locking feature of the ERC-777 provided the flexibility necessary to work well within the SKALE Manager, which consists of ~36 Solidity contracts, including the SKALE Token, which all manage the flow of delegation validator staking requirements, and SKALE Chain staking requirements involving the SKALE token.

More details about the SKALE token are here: https://skale.network/token/

=== Where can I see the token schedule?

The token schedule is here: https://supply.skale.network/supply/index.html
—> month 0 is Oct. 2020.

=== What's an epoch?

One epoch on SKALE equals **one-month calendar period** of network activity.
Validator and delegator rewards are calculated and distributed at the end of each epoch. Epochs start on the 1st day of each month and end on the last day of each month.

Please note that the delegation period can be longer than an epoch.

=== Has SKALE conducted any audit of its code?

SKALE Manager and IMA contracts are periodically audited by third parties and have been audited independently by ConsenSys Diligence, Quantstamp, and Bramah Systems. See each repository for further details.

SKALE Network also has an active HackerOne program. Please see the SKALE Network's HackerOne program for any bug bounties related to SKALE Manager: https://hackerone.com/skale_network

=== How do SKALE Chains resist DDoS attacks and malicious activity?

The SKALE Network has a few ways to handle DDoS protections, xref:skaled::index.adoc#_ddos_protection[more details here].

High load monitoring and prevention outlined in the above documentation under the DDoS Protection section provides a detailed explanation of the feature.

Additionally, SKALE Chains still have SKALE chain-specific ETH (skETH) that helps to prevent malicious activity. Here is an excerpt from the dev documentation above:

```
Transactions on SKALE Chain run in a gas-free way. This means there is gas on 
SKALE Chains just like on Ethereum, but it's powered by what's called SKALE ETH
(skETH), which has no monetary value. In this way, executing transactions and 
state changes don't incur costs but require consuming gas in skETH, which is 
value-less. SKALE Chain gas provides a way to meter or limit transactions on the
SKALE Chain to prevent malicious execution.
```

=== How does the network mitigate security risks?

Security and validity of transactions in a sidechain primarily rest with the performance and behavior of the validator nodes. A network first has to have a heterogeneous set of validator nodes. A small number of nodes in a network is inherently risky and fragile.

In addition, and as a requirement for a secure and robust network, it ideally needs to provide for a) the random selection of chain validator sets and b) the rotation of nodes in and out of chains frequently. Without randomness and rotation, there is a far greater risk of bribery or collusion between validators, reducing the security and integrity of the chains within a network.

== Have an unanswered question?  

**http://skale.chat[Head over to the SKALE Developer community!]**