= SKALE Chain ETH

SKALE Chains enable dApps to run gasless transactions. This provides an effective way to scale your dApp not only for speed but also to scale economically. However, SKALE Chains do require skETH to conduct transactions – this skETH is SKALE Chain "fake" ETH with no economic value but provides a way for dApps to facilitate permissive access to SKALE Chains and protects against DDoS attacks.

There are a few ways to get SKALE ETH (skETH), depending on your setup.

== ETH on SKALE SDKs

For SKALE SDKs, an account is pre-funded with SKALE ETH (skETH). You can use this for conducting transactions, sending to users on your SKALE Chain, and more. See the README in the respective SDK for the pre-funded account, or check your `.env` file setup.

== skETH on Mainnet and Dappnet SKALE Chains

For Mainnet and Dappnet, the SKALE Chain owner account is provided skETH for the SKALE Chain. From this account, the owner can fund contracts, accounts, conduct transactions, etc. When end-users complete transactions and spend gas, the coinbase account is refunded with gas. The coinbase account for SKALE chains is the SKALE Owner account.

== Real ETH on SKALE Chains

To view Real ETH on SKALE Chains, as in the amount locked in IMA DepositBoxes, you can use the _informational RPC ports_ for your endpoint. 