= SKALE Chain FUEL (sFUEL)
:experimental:

SKALE Chains enable dApps and their users to run scalable, zero-gas cost transactions using SKALE Chains' native token sFUEL. sFUEL effectively allows developers to scale their dApp not only for speed but also to scale economically and provides users with an optimal user experience. 

SKALE Chains require users to have sFUEL to conduct transactions. This sFUEL is a zero-cost gas token with no economic value and provides a way for dApps and users to access SKALE Chains and protects against DDoS attacks.

[NOTE]
Be careful not to confuse SKALE chain native sFUEL tokens with the SKALE Network token SKL, a mixed-use token representing the right to work in the network as a validator, stake as a delegator, or access a share of its resources by deploying and renting a SKALE Chain over time as a developer.

== How to get sFUEL

Each chain or dApp in the SKALEverse has its process and endpoints for distributing sFUEL to users. Often sFUEL is distributed to users through each dapp's onboarding process.

Alternatively, you can use the sFUEL station to automatically sFUEL up across all supported SKALE chains: https://sfuel.skale.network/. Enter your account address and click btn:[Fuel Wallet]. See the video below:

video::sfuel-station.m4v[opts=autoplay, height=450, width=800]

== Developing with sFUEL

Depending on the desired setup, there are several ways SKALE Network developers can manage and allocate users SKALE FUEL (sFUEL). Please see xref:develop::sfuel-gas-token.adoc[Developing with sFUEL].