= SKALE Chain FUEL

SKALE Chains enable dApps to run gasless transactions. This provides an effective way to scale your dApp not only for speed but also to scale economically. However, SKALE Chains do require sFUEL to conduct transactions – this sFUEL is a gas token with no economic value and provides a way for dApps to facilitate permissive access to SKALE Chains and protects against DDoS attacks.

There are a few ways to get SKALE FUEL (sFUEL), depending on your setup.

== sFUEL on SKALE SDKs

For SKALE SDKs, an account is pre-allocated with SKALE FUEL (sFUEL). You can use this for conducting transactions, sending to users on your SKALE Chain, and more. See the README in the respective SDK for the pre-allocated account, or check your `.env` file setup.

== sFUEL on Mainnet and Dappnet SKALE Chains

For Mainnet and Dappnet, the SKALE Chain owner account is provided sFUEL for the SKALE Chain. From this account, the owner can fund contracts, accounts, conduct transactions, etc. When end-users complete transactions and spend gas, the coinbase account is refunded with sFUEL. The coinbase account for SKALE Chains is the SKALE Owner account.

== Real ETH on SKALE Chains

To view Real ETH on SKALE Chains, as in the amount locked in IMA DepositBoxes, you can use the _informational RPC ports_ for your endpoint. 