= Setup SKALE IMA SDK

The IMA SDK provides a locally hosted environment for developing with the SKALE IMA Bridge. Two chains are provided on different ports: on Ganache 8545, the Ethereum side IMA contracts such as DepositBoxes are deployed, and on SKALED Port 15000, the SKALE Chain side IMA contracts such as TokenManagers are deployed.

This IMA SDK works for Mac, Windows, and 64-bit Linux.

== Get Started with the IMA SDK

. Ensure that the following prerequisites are installed:
* docker
* docker-compose (https://docs.docker.com/compose/install/)
* nodejs (>12)
* _optional: domain name + SSL certificates if you wish to use https endpoints_

. Clone the IMA SDK repository
+
```shell
git clone https://github.com/skalenetwork/skale-ima-sdk
cd skale-ima-sdk
```

. Copy the .env template and add your accounts:
+
```shell
cp .env-compose-sample .env
nano .env
``` 

. Export the environment variables:
+
```shell
export $(grep -v '^#' .env | xargs)
```

. (OPTIONAL) Place SSL cert & key in `ssl` folder:
+
[NOTE]
Names must be `ssl_key` and `ssl_cert`:
+
```shell
cp privkey.pem ~/skale-ima-sdk/ssl/ssl_key
cp cert.pem ~/skale-ima-sdk/ssl/ssl_cert
```

. Startup the SDK and deploy IMA contracts to local ganache and Skaled:
+
```shell
WAIT=True bash scripts/run_sdk.sh
```
+
Output:
+
```shell
Updating skaled configuration file
Will load JSON file "/Users/cskale/Projects/skale-ima-sdk/config0.json"...
Did loaded content of JSON file "/Users/cskale/Projects/skale-ima-sdk/config0.json", will parse it...
Done, loaded content of JSON file "/Users/cskale/Projects/skale-ima-sdk/config0.json".
Updated chainId: -4
Address 0x66c5a87f4a49DD75e970055A265E8dd5C3F8f852 is already in accounts section
Will save JSON file "/Users/cskale/Projects/skale-ima-sdk/config0.json"...
Done, saved content of JSON file "/Users/cskale/Projects/skale-ima-sdk/config0.json".
Done.
Creating ima_sdk         ... done
Creating ima_sdk_ganache ... done
Mainnet contracts deployed: /Users/cskale/Projects/skale-ima-sdk/scripts/../contracts_data/proxyMainnet.json
Waiting for sChain contracts 0/100
Waiting for sChain contracts 1/100
...

```
+
You can check that both the `ima_sdk_ganache` and `ima_sdk` containers are up by executing:
+
```shell
docker ps -a
```

. Wait for completion of IMA contract deployments and startup of the IMA Agent. You can check the progress as follows:
+
```shell
docker logs ima_sdk_ganache
```
+
You should see this final line in the log outputs: `Listening on 0.0.0.0:8545`
+
```shell
docker logs ima_sdk
```
+
And you should see this complete final output before using the sdk:
+
```shell
...
Will start SKALE Chain...
Successfully started SKALE Chain
 
Will deploy IMA to Main Net...
Successfully deployed IMA to Main Net...
 
Will deploy IMA to S-Chain...
Successfully deployed IMA to SKALE Chain...
 
Will register IMA...
Successfully registered IMA.
 
Will start IMA agent transfer loop...
Successfully started IMA agent transfer loop
 
Press any key to stop this docker container
```
+
You can also test the Ganache using `geth attach`:
+
```shell
geth attach http://127.0.0.1:8545
```
+
Should output:
+
```shell
Welcome to the Geth JavaScript console!

instance: EthereumJS TestRPC/v2.11.3-beta.0/ethereum-js
coinbase: 0x98664cee8831d7a61d394d7e10207df074e5a895
at block: 0 (Mon Aug 16 2021 14:58:31 GMT-0700 (PDT))
 modules: eth:1.0 evm:1.0 net:1.0 personal:1.0 rpc:1.0 web3:1.0
```
+
And attaching to the SKALE chain:
+
```shell
geth attach http://127.0.0.1:15000
```
+
Should output:
+
```shell
Welcome to the Geth JavaScript console!

instance: skaled/3.7.3+commit.ecaa2572/linux/gnu7.5.0/debug
coinbase: 0x66c5a87f4a49dd75e970055a265e8dd5c3f8f852
at block: 40 (Mon Aug 16 2021 15:01:55 GMT-0700 (PDT))
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 skale:0.1 skaleDebug:1.0 skaleStats:1.0 web3:1.0
```

== Working with the SDK

=== Access ABIs

The ABIs generated for the IMA contracts deployed to Ganache and the SKALE Chain are found here:

```shell
skale-ima-sdk/contracts_data/proxyMainnet.json # Mainnet part
skale-ima-sdk/contracts_data/proxySchain_Bob.json # sChain part
```

=== Endpoints

```shell
# sChain
http://$IP_ADDRESS:15000
http://$DOMAIN_NAME/schain # if you have SSL certs and domain name
https://$DOMAIN_NAME/schain # if you have SSL certs and domain name
# Mainnet
http://$IP_ADDRESS:1545
http://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
https://$DOMAIN_NAME/mainnet # if you have SSL certs and domain name
```

_docs in progress_

== Using the IMA Bridge

Please refer to the main xref:ima::index.adoc[IMA Bridge documentation here].

== Stopping the SDK

```shell
CLEANUP=True  bash scripts/stop_sdk.sh
```

== Troubleshooting

If you encounter any issues, be sure to stop and remove the docker containers, and execute `./clean.sh`.

You can inspect the `data_dir/all_ima_*.txt` files for logs of the startup process.
