= Developing on SKALE

== Quick Start

Already an Ethereum developer? Use all your usual tools and deployment methods (Truffle, Hardhat, Remix, Web3) and get your own SKALE Chain RPC Endpoint. Yes - an entire RPC endpoint for your dApp, end-users, and ecosystem.

=== Get a SKALE Endpoint

There are several types of SKALE RPC endpoints to get depending on your development stage: development, network testing, and mainnet.

**🧑‍💻 For quick development**, a single-node chain is sufficient and recommended to build and test your dApp on a SKALE Chain with IMA and Filestorage. 

.Local and IMA-Bridge development environment
* ⛓ SKALE Chain + IMA Bridge: xref:ima-sdk.adoc[Use the SDK instructions here].

**✅ For network and load testing**, a multi-node chain is recommended.

.SKALE Dappnet-Rinkeby development environments
* Request a multi-node Dappnet SKALE Chain with IMA connected to Ethereum Rinkeby
* https://skale.network/innovators-signup[Request to join the SKALE Innovator Program] to access a multi-node Dappnet SKALE Chain

**🚀 For production ready dApps**, SKALE Mainnet Chains are currently available to select dApps, and will be available on a rolling basis.

.SKALE Mainnet
* Receive a grant to provision a 16-node SKALE Chain on Mainnet
* (Soon) Stake SKL to provision a 16-node SKALE Chain on Mainnet

* Setup Web3 wallets to work with the RPC Endpoint

* Deploy your contracts on your SKALE Endpoint

== Existing dApps

You can deploy your contracts over to your SKALE Chain and begin to use faster and zero-cost gas transactions. Depending on your architecture and needs, you may want to evaluate which contracts to keep on Ethereum and which to serve on SKALE, such as putting more end-user facing transactions on SKALE and transactions requiring PoW security on Ethereum.

[NOTE]
SKALE Chains have unique access control features. New SKALE Chains only permit the SKALE Chain owner the ability to deploy contracts. See xref:skale-chain-access-control.adoc[SKALE Chain Access Control] for more information. 

For using the Ethereum-SKALE bridge called Interchain Messaging Agent, you can customize your own bridge and map tokens you select to support, or enable automatic mapping.

To enable existing contracts to interact with the messaging layer, you'll have to add an interface to communicate with the IMA MessageProxy layer. 

Already have an ERC-721 on Mainnet? You can use the IMA extension contracts to enable any new tokens minted on SKALE to be minted on Ethereum while preserving the URI and original Minter address on mainnet. 

== New dApps

== Developer Tool Docs

* https://www.trufflesuite.com/docs[Truffle Suite Docs]
* https://remix-ide.readthedocs.io/en/latest/#[Remix Docs]
* https://docs.openzeppelin.com/[OpenZeppelin Docs]


== Basics of dapp Development

* https://cryptozombies.io/[CryptoZombies]
* https://solidity-by-example.org[Solidity By Example]
* https://docs.soliditylang.org/[Solidity Docs] and see https://docs.soliditylang.org/en/v0.8.6/#translations[Solidity Docs translations]
* https://ethereum.org/en/developers/[Ethereum Developer Resources]

== Best Practices

* https://consensys.github.io/smart-contract-best-practices/[Ethereum Smart Contract Security Best Practices]
* https://consensys.net/diligence/blog/2020/11/token-interaction-checklist/[ConsenSys Diligence's Token Interaction Checklist]