= Developing on SKALE

== Quick Start

Already an Ethereum developer? Use all your usual tools and deployment methods (Truffle, Hardhat, Remix, Web3) and get a SKALE Chain RPC Endpoint. 

=== Get a SKALE Endpoint

For testing, you can use the SKALE public testnet which has 15 chains. Most of these chains are dedicated to other dApps and hubs, except for the CHAOS chain (`staging-fast-active-bellatrix`) which is provided for general public testing.

[cols="h,m"]
|===
|Chain Name: |staging-fast-active-bellatrix
|RPC (https):| \https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix
|RPC (wss): | wss://staging-v3.skalenodes.com/v1/ws/staging-fast-active-bellatrix
|Block Explorer: | \https://staging-fast-active-bellatrix.explorer.staging-v3.skalenodes.com
|Chain ID: | 0x50877ed6
|Chain ID (dec): | 1351057110
|Chain Name Hash: | 0x0000050877ed6397218923b67054bfcfd054c0012d0682fe896667859b4dede9
|sFUEL Faucet: | \https://sfuel.skale.network/staging/chaos
|===


[NOTE]
====
The public chain provided above requires sFUEL to deploy contacts and perform transactions (faucet: https://sfuel.skale.network/staging/chaos). This is unlike other SKALE chains which require both xref:skale-chain-access-control.adoc#_whitelist[deployer access] and sFUEL to deploy contracts.

➡️ sFUEL is a zero-cost gas token and is the native token for each SKALE chain. xref:sfuel-gas-token.adoc[Read more about sFUEL here].
====

To view the testnet chains, go to https://staging-v3.skalenodes.com/.

== Add SKALE Chaos Testnet to MetaMask


video::798584275[vimeo, opts=autoplay, height=450, width=800]

== Existing dApps

You can deploy your contracts over to your SKALE Chain and begin to use faster and zero-cost gas transactions. Depending on your architecture and needs, you may want to evaluate which contracts to keep on Ethereum and which to serve on SKALE, such as putting more end-user facing transactions on SKALE and transactions requiring PoW security on Ethereum.

[NOTE]
SKALE Chains have unique access control features. New SKALE Chains only permit the SKALE Chain owner the ability to deploy contracts. See xref:skale-chain-access-control.adoc[SKALE Chain Access Control] for more information.

For using the Ethereum-SKALE bridge called Interchain Messaging Agent, you can customize your own bridge and map tokens you select to support, or enable automatic mapping.

To enable existing contracts to interact with the messaging layer, you'll have to add an interface to communicate with the IMA MessageProxy layer. 

Already have an ERC-721 on Mainnet? You can use the IMA extension contracts to enable any new tokens minted on SKALE to be minted on Ethereum while preserving the URI and original Minter address on mainnet. 

== New dApps

Whether starting a new project or migrating from another EVM Chain, checkout some of the tools and resources below or head over to the xref:recipes::index.adoc[Recipes] and start deploying smart contracts in minutes. 

== Developer Tool Docs

* https://hardhat.org/hardhat-runner/docs/getting-started[Hardhat Docs]
* https://www.trufflesuite.com/docs[Truffle Suite Docs]
* https://remix-ide.readthedocs.io/en/latest/#[Remix Docs]
* https://docs.openzeppelin.com[OpenZeppelin Docs]

== Basics of dapp Development

* https://cryptozombies.io[CryptoZombies]
* https://solidity-by-example.org[Solidity By Example]
* https://docs.soliditylang.org[Solidity Docs] and see https://docs.soliditylang.org/en/v0.8.6/#translations[Solidity Docs translations]
* https://ethereum.org/en/developers[Ethereum Developer Resources]

== Best Practices

* https://consensys.github.io/smart-contract-best-practices[Ethereum Smart Contract Security Best Practices]
* https://consensys.net/diligence/blog/2020/11/token-interaction-checklist[ConsenSys Diligence's Token Interaction Checklist]
