= Proof of work (PoW) 

:stem: asciimath

SKALE chain owner has several methods to top up any address with sFUEL:
* directly send sFUEL from the account,
* send transaction to Etherbase to recharge sFUEL to any address, or 
* use PoW.

PoW is a mechanism which allows SKALE chain owner to mine sufficient amount of sFUEL to any address to send transaction, if address does not have enough amount of sFUEL. The next paragraphs will describe specifics of the mechanism.

== PoW Usage

. The client generates a unique gasPrice value based on the transaction data (<<pow-algorithm, the algorithm is described below>>).

. The client sends transaction with a unique gasPrice value and the required gasAmount, which was calculated during the algorithm.

. GasPrice and gasAmount of this transaction will be checked on the SKALE chain side by the same check in the algorithm.

. Transaction is executed, even without sFUEL in the client's account.

== PoW algorithm

. The Ñlient generates a random 256-bit *X* by Formula which is equal a unique gasPrice value
+
[latexmath]
++++
hash = sha(address)\oplus sha3(nonce)\oplus sha3(gasPrice)
++++
+
[latexmath]
++++
freeGas = ( 2^{256} - 1)/hash/difficulty
++++


. Check whether *X* is allow to run transaction:
+
[latexmath]
++++
freeGas(X) > estimateGas(tx)
++++
+
a) If not, then back to the first step
+
b) If the condition is met - send the transaction with gasPrice = *X* and gasAmount = freeGas

== Control PoW on SKALE chain

* set difficulty for SKALE chain to turn on PoW mechanism

* difficulty sets the complexity of getting free gas by PoW

== PoW browser usage

* Browser wallets cannot send PoW transactions.

* You should generate `sessionKeyPair` inside the browser

* Build a transaction and run PoW client script by `sessionAddress`

* Sign and send transaction from browser signed by `sessionKey`

== Examples

https://github.com/skalenetwork/pow-demo/blob/main/skale-miner.js[Example of PoW algorithm on JS]

https://github.com/skalenetwork/pow-demo/blob/main/pow-test.js[Exapmle of sending transaction with PoW on JS]

https://github.com/skalenetwork/pow-demo/blob/main/demo.html[Example of sending transaction with PoW in browser]

