= Proof of work (PoW) 

SKALE chain owner has several methods to top up any address with sFUEL: directly send sFUEL from the account, send transaction to Etherbase to recharge sFUEL to any address or use PoW. PoW is a mechanism which allows SKALE chain owner to mine sufficient amount of sFUEL to any address to send transaction, if address does not have enough amount of sFUEL. The next paragraphs will describe specifics of the mechanism.

== PoW Usage

* Client should generate unique gasPrice value based on transaction data (Algorithm will be described below)

* Client send transaction with unique gasPrice value and required gasAmount which was calculated during the algorithm

* GasPrice and gasAmount of this transaction will be checked on SKALE chain side by the same check in the algorithm

* Transaction would be executed even without sFUEL on clients account

== PoW algorithm

1. Client generates random 256-bit *X* by Formula which is equal a unique gasPrice value

//image:https://github.com/skalenetwork 

2. Check whether *X* is allow to run transaction:

  freeGas(X) > estimateGas(tx)

a) If not, then you need to generate another one

b) If the condition is met - send the transaction with gasPrice = *X* and gasAmount = freeGas

== Control PoW on SKALE chain

* set difficulty for SKALE chain to turn on PoW mechanism

* difficulty sets the complexity of getting free gas by PoW

== PoW browser usage

* Browser wallet couldn’t send PoW transactions 

* You should generate sessionKeyPair inside browser

* Build a transaction and run PoW client script by sessionAddress

* Sign and send transaction from browser signed by sessionKey

== Examples

https://github.com/skalenetwork/pow-demo/blob/main/skale-miner.js[Example of PoW algorithm on JS]

https://github.com/skalenetwork/pow-demo/blob/main/pow-test.js[Exapmle of sending transaction with PoW on JS]

https://github.com/skalenetwork/pow-demo/blob/main/demo.html[Example of sending transaction with PoW in browser]

