= Proof of work (PoW) 

:stem: asciimath

SKALE chain owner has several methods to top up any address with sFUEL:
* directly send sFUEL from the account,
* send transaction to Etherbase to recharge sFUEL to any address, or 
* use PoW.

PoW is a mechanism which allows SKALE chain owner to mine sufficient amount of sFUEL to any address to send transaction, if address does not have enough amount of sFUEL. The next paragraphs will describe specifics of the mechanism.

== PoW Usage

. The client generates a unique gasPrice value based on the transaction data (<<pow-algorithm, the algorithm is described below>>).

. The client sends transaction with a unique gasPrice value and the required gasAmount, which was calculated during the algorithm.

. GasPrice and gasAmount of this transaction will be checked on the SKALE chain side by the same check in the algorithm.

. Transaction is executed, even without sFUEL in the client's account.

== PoW algorithm

. The сlient generates a random 256-bit *X* by Formula which is equal a unique gasPrice value
+
[latexmath]
++++
X = sha3(address)\oplus sha3(nonce)\oplus sha3(gasPrice)
++++
+
[latexmath]
++++
freeGas = ( 2^{256} - 1)/X/difficulty
++++


. Check whether *X* is allow to run transaction:
+
[latexmath]
++++
freeGas(X) > estimateGas(tx)
++++
+
a) If not, then back to the first step
+
b) If the condition is met - send the transaction with gasPrice = X and gasAmount = freeGas(X)

IMPORTANT: KECCAK256(SHA3) hashing algorithm should be used.

== Control PoW on SKALE chain

* set difficulty for SKALE chain to turn on PoW mechanism

* difficulty sets the complexity of getting free gas by PoW

== PoW browser usage

Metamask and unlikely others browser wallets (Portis, Bitski etc) with which the SKALE Сhains is compatible cannot send PoW transactions. It happens because usually browser wallets limit a variable gasPrice and does not allow to set it higher than some threshold as it necessary for PoW.

Otherwise it is possible to top up an account from the browser wallet. There are several methods to top up an account with sFUEL, but we need to have a methods which wouldn’t require an access to the address with sFUEL.

It is possible to generate a new Ethereum account and execute transactions with PoW mechanism by the web3/ethers libraries in browser running scripts. So if it would be a contract which allows to send sFUEL to an account and can be executed by any account from the network(with sFUEL or using PoW mechanism) then we can top up an account from the any web3 browser wallets.

== PoW browser usage algorithm

1. A contract with a function which can transfer funds to some address as a “Payer” contract in an example should be deployed by SKALE chain owner address
2. New Ethereum account (sessionKey) should be created outside of browser wallet 
3. Sign & Send transaction from this new Ethereum account (sessionKey) to execute a function in a contract with using PoW mechanism.

== Examples

https://github.com/skalenetwork/pow-demo/blob/main/skale-miner.js[Example of PoW algorithm on JS]

https://github.com/skalenetwork/pow-demo/blob/main/pow-test.js[Exapmle of sending transaction with PoW on JS]

https://github.com/skalenetwork/pow-demo/blob/main/demo.html[Example of sending transaction with PoW in browser]

