= SKALE Chain Wallet

The SKALE Network uses a "self-reimbursing" wallet system to make it easier for SKALE Chain Owners to reimburse certain node-related transactions that are executed on Ethereum. The use of self-recharging wallets is a requirement for testnet and mainnet.

The Wallets contract in SKALE Manager manages this functionality.

Each SKALE Chain owner manages a wallet. This wallet must contain a balance of ETH that's used to reimburse specific transactions performed by validator-nodes including certain IMA messages.

Transactions that are reimbursed by the schain owner are:

* certain SKALE Chain distributed key generation operations
* _contingent_ reimbursement of bridge exits, see section below <<_ima_bridge>>.


Anyone can fund the SKALE Chain wallet, but only the SKALE Chain owner may withdraw funds from the SKALE Chain wallet after the SKALE Chain deletion process has begun.

== IMA Bridge

If using the IMA bridge with Ethereum, the SKALE Chain owner and community must ensure the SKALE Chain owner ETH balance is sufficient to ensure proper bridge messaging and transaction gas reimbursement. 

[plantuml]
....
@startuml

box "SKALE Network"
participant "IMA Schain" as IS
participant "SKALE Node" as SN
end box

box "Ethereum"
participant "IMA\nCommunity Pool" as CP
participant "IMA\nMainnet" as IM
participant "SKALE Manager\nWallets" as SMW
end box

IS -> CP : 1. User deposits ETH IMA Community Pool
IS -> IM : 2. User exits
SN -> IM : 3. Random SKALE node posts tx
CP -> SN : 4. Reimbursement from user's community pool
SMW --> SN : 5. Contingent reimbursement

@enduml
....

Each end-user reimburses validator-nodes for IMA messaging with Ethereum. This reimbursement is performed from the end-user's balance in the Community Pool contract on Ethereum mainnet. In the extraordinary situation where an end-user's Community Pool balance is insufficient, part or all the costs will be provided by the SKALE Chain wallet to ensure proper transaction processing. When this happens, the end-user will be locked from further exits until the end-user reimburses their Community Pool ETH balance. 

[NOTE]
For details on the end-user IMA exit process to Ethereum, see xref:ima::funding-exits.adoc[Funding Exits].

The minimum recommended ETH balance in the SKALE Chain wallet for IMA messaging is (`MESSAGES_LENGTH * gasLimit * tx.gasPrice`) where global settings define `MESSAGES_LENGTH` as 10+1 and gasLimit as `1,000,000` gas. For example, if the Ethereum network gas cost is 200 Gwei, the SKALE Chain Wallet balance must contain (`11 * 1000000 * 200`) = 2.2 ETH. If the network gas cost > 200 Gwei and the SKALE Chain wallet balance is ≤ 2.2 ETH, IMA messages will pause until the gas costs are ≤ 200 Gwei, or the SKALE Chain wallet balance is > 2.2 ETH.

Any community member can recharge the SKALE Chain wallet with additional ETH, or end-users may wait for the Ethereum network gas costs to decrease. Once the SKALE Chain wallet is recharged, stuck messages will resume. If there is a large queue, additional time will be required to clear the queue.
