= Wallets

SKALE Chains can work with a variety of wallet solutions, including any Web3 based solution such as:

* Metamask
* Portis
* Bitski
* Torus
* Magic
* Wallet Connect

Want another wallet tool listed here? https://skale.network/roadmap[Submit a new idea].

== Metamask

Metamask is a Chromium (Chrome, Brave, and Edge) and Firefox browser add-on that provides a non-custodial Ethereum wallet. An end-user's private key is stored in an encrypted Vault data stored in the browser.

It can also connect to hardware based wallets such as Ledger. 

https://medium.com/mycrypto/how-to-ensure-youre-running-the-legitimate-version-of-metamask-5fcd8ab32b96[Please be sure you and your end-users are running a legitimate version of Metamask!] 

Metamask allows you to integrate your dApp with SKALE by setting the Network RPC endpoint for your users. For more information and support, see <https://consensys.net/blog/metamask/connect-users-to-layer-2-networks-with-the-metamask-custom-networks-api>

=== Install the NPM Packages

```shell
npm install --save web3
```

=== Example Code

```javascript
import Web3 from 'web3';

let web3 = "";

let switchToSKALE = {
  chainId: "0x54173", //decodes to 344435
  chainName: "SKALE Network Testnet",
  rpcUrls: ["https://dev-testnet-v1-0.skalelabs.com"],
  nativeCurrency: {
    name: "SKALE ETH",
    symbol: "skETH",
    decimals: 18
  },
  blockExplorerUrls: [
    "https://expedition.dev/?rpcUrl=https://dev-testnet-v1-0.skalelabs.com"
  ]
};

web3 = window.web3;

  if (window.ethereum) {
    window.web3 = new Web3(window.ethereum);
    try {
      // Request account access if needed
      await window.ethereum.enable();
      console.log("MetaMask - Web3 Initialized!");

      //Get user wallet accounts
      window.web3.eth.getAccounts((error, accounts) => {
        if (error) {
          console.error(error);
        }
        console.log(accounts);

        //request change to SKALE Network
        window.ethereum
          .request({
            method: "wallet_addEthereumChain",
            params: [switchToSKALE, accounts[0]]
          })
          .catch((error) => console.log(error.message));
      });
    } catch (error) {
      // User denied account access...
    }
  }
  // Legacy dapp browsers...
  else if (window.web3) {
    window.web3 = new Web3(web3.currentProvider);
    console.log("MetaMask - Web3 Initialized!");
  }
  // Non-dapp browsers...
  else {
    console.log(
      "Non-Web3 browser detected. You should consider trying MetaMask!"
    );
  }
```

=== Example Sandbox

<https://codesandbox.io/s/metamask-wallet-integration-skale-dev-docs-k77zj>

== Portis

Portis is a non-custodial Web3 wallet SDK supported by a variety of "evergreen" browsers. The Portis SDK allows you to integrate your dApp with SKALE. 

For more information and support, see <https://docs.portis.io/#/quick-start>

=== Install the NPM Packages

```shell
npm install --save web3 @portis/web3
```

=== Example Code

```javascript
import Portis from '@portis/web3';
import Web3 from 'web3';


// Your setup information
const endpoint = 'https://your.skale.endpoint'; // your SKALE Chain endpoint
const skaleChainId = 123456                     // chainId of your SKALE Chain
const testAPIKey = 'your_api_key';

const mySKALEChain = {
    nodeUrl: endpoint,
    chainId: skaleChainId,
    nodeProtocol: "rpc"
}

// Setting network
const portis = new Portis(testAPIKey, mySKALEChain);
let web3 = new Web3(portis.provider);
```

=== Example Sandbox

<https://codesandbox.io/s/portis-wallet-integration-skale-dev-docs-41knv>

== Bitski

Bitski is a non-custodial OAuth-based Web3 wallet SDK. The Bitski SDK allows you to integrate your dApp with SKALE. 

For more information and support, see <https://docs.bitski.com/>

=== Install the NPM Packages

```shell
npm install --save web3 bitski
```

=== Example Code

```javascript
import { Bitski } from 'bitski';
import Web3 from 'web3';


// Your setup information
const endpoint = 'https://your.skale.endpoint'; // your SKALE Chain endpoint
const skaleChainId = 123456                     // chainId of your SKALE Chain
const testAPIKey = 'your_client_id';
const callbackUrl = 'https://your.app/oath-callback.html';

const bitski = new Bitski(
    testAPIKey,
    callbackUrl
);

const network = {
    rpcUrl: endpoint,
    chainId: skaleChainId,
}

// Setting network
const provider = bitski.getProvider({ network });
let web3 = new Web3(provider);
```

=== Example Sandbox

<https://codesandbox.io/s/bitski-wallet-integration-skale-dev-docs-s3uor>

== Torus

The Torus Wallet provides a non-custodial OAuth-based wallet Web3 interface that works with an iframe, and allows you to integrate your dApp with your SKALE Chain.

For more information and support, see <https://docs.tor.us/torus-wallet/quick-start> and <https://docs.tor.us/how-torus-works/torus-wallet>.

=== Install the NPM Packages

```shell
npm install --save web3 @toruslabs/torus-embed
```

=== Example Code

```javascript
import Portis from '@toruslabs/torus-embed';
import Web3 from 'web3';


// Your setup information
const endpoint = 'https://your.skale.endpoint'; // your SKALE Chain endpoint
const skaleChainId = 123456                     // Optional SKALE Chain chainId
const network = "SKALE Network";                // Optional network name

// Setting network
const torus = new Torus()
await torus.init(
    {
        network: {
            host: endpoint,
            chainId: skaleChainId,
            networkName: network
        }
    }
);
await torus.login(); // await torus.ethereum.enable()
const web3 = new Web3(torus.provider);
```

=== Example Sandbox

<https://codesandbox.io/s/torus-wallet-integration-skale-dev-docs-soj6n>

== Magic Wallet (Fortmatic)

The Magic Wallet SDK leverages a non-custodial Delegated Key Management system to provide a Web3 wallet using a phone number or email for authentication. 

For more information and support, see <https://docs.fortmatic.com/web3-integration/network-configuration#switch-network-to-custom-node>

=== Install the NPM Package

```shell
npm install --save web3 fortmatic
```

=== Example Code

```javascript
import Fortmatic from 'fortmatic';
import Web3 from 'web3';


// Your setup information
const endpoint = 'https://your.skale.endpoint'; // your SKALE Chain endpoint
const skaleChainId = 123456                     // chainId of your SKALE Chain
const testAPIKey = 'your_test_api_key';

const customNodeOptions = {
    rpcUrl: endpoint, 
    chainId: skaleChainId 
}

// Setting network
const fm = new Fortmatic(testAPIKey, customNodeOptions);
let web3 = new Web3(fm.getProvider());
```

=== Example Sandbox

<https://codesandbox.io/s/fortmatic-wallet-integration-skale-dev-docs-moskd>

== Wallet Connect

The Wallet Connect is an open source protocol to link dApps to mobile wallets using deep linking, and allows you to integrate your dApp with SKALE.

For more information and support, see <https://docs.walletconnect.org/quick-start/dapps/web3-provider>

=== Install the NPM Packages

```shell
npm install --save web3 @walletconnect/web3-provider
```

=== Example Code

```javascript
import WalletConnectProvider from "@walletconnect/web3-provider";
import Web3 from 'web3';


// Your setup information
const endpoint = 'https://your.skale.endpoint';             // your SKALE Chain endpoint
const ethereumEndpoint = 'https://your.ethereum.endpoint'   // your Ethereum endpoint
const skaleChainId = 123456                                 // chainId of your SKALE Chain

const provider = new WalletConnectProvider({
    rpc: {
      skaleChainId: endpoint,
      4: ethereumEndpoint
    }
  });
  await provider.enable();
  const web3 = new Web3(provider);
```

=== Example Sandbox

<https://codesandbox.io/s/wallet-connect-wallet-integration-skale-dev-docs-forked-5xq08>