= A Primer on the SKALE DAO

include::partial$early.adoc[]

In brief:

* SKALE Network is a decentralized and modular EVM compatible multichain network that scales Ethereum transactions. Developers use SKALE Chains to build and deploy performant and user-centric decentralized applications.
* The distribution and staking of the $SKL hybrid utility token enables decentralized governance of SKALE Network.
* Staked $SKL tokens enable voting on SKALE DAO governance proposals, thereby facilitating $SKL delegators to collaboratively guide the evolution of SKALE.

== A Refresher on SKALE Network

SKALE Network is a high-performance, cost-effective blockchain network that complements Ethereum. Developers utilize SKALE to build user-friendly and performant decentralized applications (dApps) benefiting from the scalability offered by the SKALE Network.

Launched in 2020, the SKALE Network has continuously improved its performance and scalability. The $SKL hybrid utility tokens facilitate decentralized control over the SKALE Network and its underlying infrastructure. Staked $SKL tokens permit voting on SKALE DAO governance proposals, enabling $SKL token holders who stake to influence the future of SKALE collectively.

== What is governance?

Governance refers to decision-making processes and actions by which systems update and maintain themselves. Traditional governance in companies, governments, and institutions involves a decision making process that is relatively centralized and permissioned - for example processes that are made by a board of directors elected by shareholders.

Web3 technologies, like SKALE's protocols and chains, are initially developed by companies but progressively become decentralized with the growth of a user and stakeholder community. This progressive decentralization typically involves DAO formation and launching a process by which certain stake holders may vote. In this way, The SKALE DAO, a decentralized autonomous organization, has decision-making authority over the SKALE Network and its associated technologies. To steer the SKALE DAO, staking $SKL tokens signifies DAO membership. Staked token holders can vote on DAO proposals.

== How can I participate ? 

* xref:delegators::index.adoc[Delegate to a SKALE validator]. 
* Vote on https://snapshot.org/#/skale.eth[SKALE DAO proposals]. 
* Become a xref:validators::index.adoc[SKALE Network validator].
* Participate in governance discussions on the https://forum.skale.network[SKALE Network forum].
* Join the https://discord.gg/skale[SKALE Community on Discord].


