= Dynamic NFT Creation

The following recipe will guide you down an in-depth process around not only using on-chain randomness, but also around
using the blockchain for more that the average NFT does. If you are new to SKALE, heade over to the xref:introduction::overview.adoc[Introduction] to learn more and if you are new to Solidity, checkout the new xref:../solidity/index.adoc[Solidity 101] section to get up and running quickly.

The following recipe will make use of a number of different packages, technologies, and tools:

* Node.js for Deploying and Interacting with contracts
* Hardhat for Smart Contract Development, Deployment, and Interaction
* Community Packages such as link:https://www.npmjs.com/package/@dirtroad/skale-rng[SKALE RNG]
* SKALE Chaos Testnet

This recipe has three sections: Setup, Contracts, Frontend. Each section will be a mini-tutorial that links to the previous section.

== Setup

This section will focus on setting up the project. You must have Node.js installed on your computer.

=== Create Project Directories

To start, run the following in your command prompt:

```shell
mkdir dynamic-nft-creation dynamic-nft-creation/smart-contracts && cd dynamic-nft-creation/smart-contracts
```

In the final section we will create a folder for the frontend (dApp), however, for now this will allow us to start.

=== Create Hardhat Project

Next run 

```shell
npx hardhat
```
in your command prompt. If you do not have Hardhat installed globally you will need to accept first. If you do then you should see three (3) options to create a new Hardhat project in your current directory. For this Recipe we will be using TypeScript. Select the second option __Create a Typescript Project__ and press enter at each prompt to create the hardhat project in your smart-contracts directory with the .gitignore file and all of the dependencies.

=== Cleanup the Project
The next step is to cleanup the project since it comes with a few defaults that we don't want in there.

Run the following to remove the unnecessary default files and the scripts folder:

```shell
rm contracts/Lock.sol scripts/deploy.ts test/Lock.ts && rmdir scripts
```

Next run the following to add in the files and folders that we want:

```shell
mkdir deploy && touch contracts/DynamicNFT.sol test/DynamicNFT.ts deploy/deploy.ts
```

=== Install Necessary Dependencies
Run the following in your command prompt to install the packages we will use:

```shell
npm add @openzeppelin/contracts @dirtroad/skale-rng dotenv && npm add -D hardhat-deploy hardhat-deploy-ethers
```

* @openzeppelin/contracts - Battle-tested smart contract contracts and libraries
* @dirtroad/skale-rng - SKALE Random Number Generator Smart Contract
* dotenv - Access to the environment within scripts. Will use values from the .env file
* hardhat-deploy & hardhat-deploy-ethers - Hardhat plugins to simplify contract deployment and post-deployment access

=== Configure Hardhat

This section will cover setting up the Hardhat Configuration file. Open the __hardhat.config.ts__ file in your favorite editor or command prompt.
Update it so that it looks the same as the following:

```typescript
import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import "hardhat-deploy";
import "hardhat-deploy-ethers";
import dotenv from "dotenv";

/*
 * Allows the script to access process.env
 */
dotenv.config();

/**
 *
 * This section checks for a PRIVATE_KEY value in the .env file
 * If no value is found it will throw the error
 */

const PRIVATE_KEY: string | undefined = (process.env.PRIVATE_KEY as string | undefined);
if (!PRIVATE_KEY) {
    throw new Error("Private Key Not Found");
}

const config: HardhatUserConfig = {
    defaultNetwork: "chaos",
    solidity: "0.8.19",
    namedAccounts: {
        deployer: 0
    },
    networks: {
        chaos: {
            accounts: [PRIVATE_KEY],
            url: "https://staging-v3.skalenodes.com/v1/staging-fast-active-bellatrix"
        }
    }
};

export default config;
```

=== Add Private Key
Now that the Hardhat Configuration file is setup properly, create an Environment Variables file in the root of the directory.

```shell
touch .env
```

Inside this file, add a single line for the PRIVATE_KEY. Add in your private key to this field after the equals sign.

[IMPORTANT]
Make sure that your .gitignore file contains **.env** on one of the lines. If you followed this section from the start it should already be included.
This will ensure that your private key is not checked into version control.

[NOTE]
The private key should not start with 0x.

```shell
PRIVATE_KEY=0123456....123456
```