= The SKALE Hubs

include::partial$what-is-a-skale-hub.adoc[]

== The Importance of Hubs

SKALE Chains are very powerful. Most projects will not need the total resources of a SKALE Chain. However, they can still benefit from the power of SKALE by joining a SKALE hub. 
Hubs leverage a shared compute model similar to traditional cloud computing. For example, many projects use shared servers when using popular cloud providers, as they 
do not need a whole server. However, as projects grow, they may need dedicated resources as they scale up to their server. SKALE enables projects to 
build in a similar style where upon outgrowing a chain, they can migrate to their own.

== Active Hubs

The following are the hubs available on the SKALE Network. Each hub is controlled by various teams in the developer community and represent a location for applications building in the same space to operate and share resources.

=== Community Hub | Titan

include::partial$hub-community.adoc[]

=== DeFI Hub | Europa

include::partial$hub-defi.adoc[]

=== Gaming Hub | Nebula

include::partial$hub-gaming.adoc[]

=== NFT Hub | Calypso

include::partial$hub-nft.adoc[]

=== Open Testnet | Chaos

include::partial$hub-open-testnet.adoc[]