= Overview

SKALE Filestorage is available on each SKALE Chain. This feature lets developers leverage specialized storage resources on the nodes that operate a SKALE Chain nodes to store data in a validated and secure manner that is in addition to the onchain data within the SKALE Chain.

To get started, checkout the xref:filestorage.js::index.adoc[Filestorage JS] NPM Library.

== Upgradeability

SKALE Filestorage leverages a specialized contract to write chunks of data directly into the SKALE Chain and into the storage space. This contract can be upgraded on a per chain basis to suit any variety of functions for SKALE Chain owners.  

image::https://img.shields.io/badge/built%20with-OpenZeppelin-3677FF[built-with openzeppelin]

And of course, it's built with OpenZeppelin Upgradeability technology.

== Web3 File Server

What good are your files if you can't show them to the world? Here, the SKALE Network provides the answer. SKALE Nodes contain an NGINX server that allows your Web3 files to be served to the world. 

image::https://img.shields.io/badge/nginx-%23009639.svg?style=for-the-badge&logo=nginx&logoColor=white[]

Check out how this xref:web3-server.adoc[Web3 File Server works].

== Other Features

**Want to see another feature listed here? https://skale.network/roadmap[Submit an idea] to the SKALE Community roadmap!**
